### ISSUE TITLE
getting started (spi_as.S)

### ISSUE THREAD

**Issue by konimaru** [DavidZemon/PropWare#2]
SEND_FAST refers to slow labels (msb_first, lsb_first), this looks like it's never been tested.

Why is 32bit send disabled (as noted in comments)?

**Comment by DavidZemon** [comment]
Send_fast is working. I'm not sure when it started working, but it's been working great for SD card access for quite some time. And, thanks to your changes, it's running at 4 MHz. Still need send_fast_array and receive_fast_array though :/

**Comment by pmrobert** [comment]
Superb! Thank you!

**Comment by konimaru** [comment]
> Send_fast is working. I'm not sure when it started working, but it's been working great for SD card access for quite some time.

Well, it never uses the **_fast** functions but jumps to their slow equivalents. Provided that the latter works it will appear so does the fast one.

See lines 271/278/283/293/296/307. Those labels all point back to the _slow_ version.

![screenshot-propware-spi_as s at release-2 0 davidzemon-propware - mozilla firefox](https://cloud.githubusercontent.com/assets/7730972/6556553/954510ae-c66e-11e4-96cf-ce21053e84b2.png)

**Comment by DavidZemon** [comment]
Ah ha! Thank you for finding this. Sneaky little bug that one. The reason it hasn't appeared yet - even on my logic analyzer - is because I haven't gotten around to testing SD writes! This bug only exists in send_fast, not read_fast. I'll get it fixed next time I'm working on PropWare (hopefully tonight).

**Comment by DavidZemon** [comment]
There were a bunch of issues with that routine. All fixed now. And, thanks to your example in the receive routine I was able to increase the speed to 4 MHz.

It's still horribly slow for multi-byte routines though :(. `send_fast_array` will be the first performance improvement I make once the high-level SD code is functional (read and write)

**Comment by konimaru** [comment]
```
// MSB first fast initialization
mov temp, #32
sub temp, bitCount
shl data, temp
```
What about **ror data, bitCount**?

**Comment by DavidZemon** [comment]
The ror is a good idea. i'll go ahead and implement that one.

Using the propeller's counter module has been in the back of my head for more than a year now. But... it's so low on the priority list that I haven't taken the time to figure out exactly how yet.
