### ISSUE TITLE
Bootstrap-ify Doxygen

### ISSUE THREAD

**Issue by DavidZemon** [DavidZemon/PropWare#58]
This project looks like pure gold. Make it happen
https://github.com/Velron/doxygen-bootstrapped

**Comment by DavidZemon** [comment]
The standard search bar doesn't work with this layout, and it was also generated prior to the namespace icons. The result looks great at first glance, but degrades quickly as you look closer. I'll stick with vanilla Doxygen for now.

**Comment by pmrobert** [comment]
Not ready for prime time, huh? Better to try than not! Thank you.
