### ISSUE TITLE
Mac OS X Installation miss-spelled zip file name

### ISSUE THREAD

**Issue by dgately** [DavidZemon/PropWare#59]
propware.zip miss-spelled...

On attempting to execute the PropWare download/installation instructions on a recent Mac OS X system (10.11.2 - El Capitan), I've run into a number of issues that I'm working-through in order to assist in your creation of an install package for Mac OS X. Here's the first issue:

#1 Minor spelling issues in the instructions. Need to fix 2 typos of the misspelled " unzip prowpare.zip"   (to: 'propware.zip').

**Comment by DavidZemon** [comment]
Perfect! Thanks for reporting this. This issue will be auto-closed next time I merge release-2.0-nightly with release-2.0
